// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: relayer/chains/ethereum/config/config.proto

package ethereum

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ChainConfig struct {
	ChainId               string     `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	EthChainId            uint64     `protobuf:"varint,2,opt,name=eth_chain_id,json=ethChainId,proto3" json:"eth_chain_id,omitempty"`
	RpcAddr               string     `protobuf:"bytes,3,opt,name=rpc_addr,json=rpcAddr,proto3" json:"rpc_addr,omitempty"`
	Signer                *types.Any `protobuf:"bytes,4,opt,name=signer,proto3" json:"signer,omitempty"`
	IbcAddress            string     `protobuf:"bytes,5,opt,name=ibc_address,json=ibcAddress,proto3" json:"ibc_address,omitempty"`
	InitialSendCheckpoint uint64     `protobuf:"varint,6,opt,name=initial_send_checkpoint,json=initialSendCheckpoint,proto3" json:"initial_send_checkpoint,omitempty"`
	InitialRecvCheckpoint uint64     `protobuf:"varint,7,opt,name=initial_recv_checkpoint,json=initialRecvCheckpoint,proto3" json:"initial_recv_checkpoint,omitempty"`
	EnableDebugTrace      bool       `protobuf:"varint,8,opt,name=enable_debug_trace,json=enableDebugTrace,proto3" json:"enable_debug_trace,omitempty"`
	AverageBlockTimeMsec  uint64     `protobuf:"varint,9,opt,name=average_block_time_msec,json=averageBlockTimeMsec,proto3" json:"average_block_time_msec,omitempty"`
	MaxRetryForInclusion  uint64     `protobuf:"varint,10,opt,name=max_retry_for_inclusion,json=maxRetryForInclusion,proto3" json:"max_retry_for_inclusion,omitempty"`
	// option for ibc-solidity ADR-001
	// if set, the relayer updates a LC contract directly if possible
	// if null, the relayer updates a LC contract via the handler
	AllowLcFunctions   *AllowLCFunctionsConfig `protobuf:"bytes,11,opt,name=allow_lc_functions,json=allowLcFunctions,proto3" json:"allow_lc_functions,omitempty"`
	GasEstimateRate    *Fraction               `protobuf:"bytes,12,opt,name=gas_estimate_rate,json=gasEstimateRate,proto3" json:"gas_estimate_rate,omitempty"`
	MaxGasLimit        uint64                  `protobuf:"varint,13,opt,name=max_gas_limit,json=maxGasLimit,proto3" json:"max_gas_limit,omitempty"`
	TxType             string                  `protobuf:"bytes,14,opt,name=tx_type,json=txType,proto3" json:"tx_type,omitempty"`
	DynamicTxGasConfig *DynamicTxGasConfig     `protobuf:"bytes,15,opt,name=dynamic_tx_gas_config,json=dynamicTxGasConfig,proto3" json:"dynamic_tx_gas_config,omitempty"`
	CustomErrors       []*CustomError          `protobuf:"bytes,16,rep,name=custom_errors,json=customErrors,proto3" json:"custom_errors,omitempty"`
}

func (m *ChainConfig) Reset()         { *m = ChainConfig{} }
func (m *ChainConfig) String() string { return proto.CompactTextString(m) }
func (*ChainConfig) ProtoMessage()    {}
func (*ChainConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8a57ab2f9f14837, []int{0}
}
func (m *ChainConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ChainConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ChainConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ChainConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainConfig.Merge(m, src)
}
func (m *ChainConfig) XXX_Size() int {
	return m.Size()
}
func (m *ChainConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ChainConfig proto.InternalMessageInfo

type AllowLCFunctionsConfig struct {
	LcAddress string   `protobuf:"bytes,1,opt,name=lc_address,json=lcAddress,proto3" json:"lc_address,omitempty"`
	AllowAll  bool     `protobuf:"varint,2,opt,name=allow_all,json=allowAll,proto3" json:"allow_all,omitempty"`
	Selectors []string `protobuf:"bytes,3,rep,name=selectors,proto3" json:"selectors,omitempty"`
}

func (m *AllowLCFunctionsConfig) Reset()         { *m = AllowLCFunctionsConfig{} }
func (m *AllowLCFunctionsConfig) String() string { return proto.CompactTextString(m) }
func (*AllowLCFunctionsConfig) ProtoMessage()    {}
func (*AllowLCFunctionsConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8a57ab2f9f14837, []int{1}
}
func (m *AllowLCFunctionsConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AllowLCFunctionsConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AllowLCFunctionsConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AllowLCFunctionsConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllowLCFunctionsConfig.Merge(m, src)
}
func (m *AllowLCFunctionsConfig) XXX_Size() int {
	return m.Size()
}
func (m *AllowLCFunctionsConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_AllowLCFunctionsConfig.DiscardUnknown(m)
}

var xxx_messageInfo_AllowLCFunctionsConfig proto.InternalMessageInfo

type Fraction struct {
	Numerator   uint64 `protobuf:"varint,1,opt,name=numerator,proto3" json:"numerator,omitempty"`
	Denominator uint64 `protobuf:"varint,2,opt,name=denominator,proto3" json:"denominator,omitempty"`
}

func (m *Fraction) Reset()         { *m = Fraction{} }
func (m *Fraction) String() string { return proto.CompactTextString(m) }
func (*Fraction) ProtoMessage()    {}
func (*Fraction) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8a57ab2f9f14837, []int{2}
}
func (m *Fraction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Fraction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Fraction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Fraction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fraction.Merge(m, src)
}
func (m *Fraction) XXX_Size() int {
	return m.Size()
}
func (m *Fraction) XXX_DiscardUnknown() {
	xxx_messageInfo_Fraction.DiscardUnknown(m)
}

var xxx_messageInfo_Fraction proto.InternalMessageInfo

type DynamicTxGasConfig struct {
	LimitPriorityFeePerGas     string    `protobuf:"bytes,1,opt,name=limit_priority_fee_per_gas,json=limitPriorityFeePerGas,proto3" json:"limit_priority_fee_per_gas,omitempty"`
	PriorityFeeRate            *Fraction `protobuf:"bytes,2,opt,name=priority_fee_rate,json=priorityFeeRate,proto3" json:"priority_fee_rate,omitempty"`
	LimitFeePerGas             string    `protobuf:"bytes,3,opt,name=limit_fee_per_gas,json=limitFeePerGas,proto3" json:"limit_fee_per_gas,omitempty"`
	BaseFeeRate                *Fraction `protobuf:"bytes,4,opt,name=base_fee_rate,json=baseFeeRate,proto3" json:"base_fee_rate,omitempty"`
	FeeHistoryRewardPercentile uint32    `protobuf:"varint,5,opt,name=fee_history_reward_percentile,json=feeHistoryRewardPercentile,proto3" json:"fee_history_reward_percentile,omitempty"`
	MaxRetryForFeeHistory      uint32    `protobuf:"varint,6,opt,name=max_retry_for_fee_history,json=maxRetryForFeeHistory,proto3" json:"max_retry_for_fee_history,omitempty"`
}

func (m *DynamicTxGasConfig) Reset()         { *m = DynamicTxGasConfig{} }
func (m *DynamicTxGasConfig) String() string { return proto.CompactTextString(m) }
func (*DynamicTxGasConfig) ProtoMessage()    {}
func (*DynamicTxGasConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8a57ab2f9f14837, []int{3}
}
func (m *DynamicTxGasConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DynamicTxGasConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DynamicTxGasConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DynamicTxGasConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DynamicTxGasConfig.Merge(m, src)
}
func (m *DynamicTxGasConfig) XXX_Size() int {
	return m.Size()
}
func (m *DynamicTxGasConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_DynamicTxGasConfig.DiscardUnknown(m)
}

var xxx_messageInfo_DynamicTxGasConfig proto.InternalMessageInfo

type Argument struct {
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (m *Argument) Reset()         { *m = Argument{} }
func (m *Argument) String() string { return proto.CompactTextString(m) }
func (*Argument) ProtoMessage()    {}
func (*Argument) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8a57ab2f9f14837, []int{4}
}
func (m *Argument) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Argument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Argument.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Argument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Argument.Merge(m, src)
}
func (m *Argument) XXX_Size() int {
	return m.Size()
}
func (m *Argument) XXX_DiscardUnknown() {
	xxx_messageInfo_Argument.DiscardUnknown(m)
}

var xxx_messageInfo_Argument proto.InternalMessageInfo

type CustomError struct {
	FunctionName string      `protobuf:"bytes,1,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	Arguments    []*Argument `protobuf:"bytes,2,rep,name=arguments,proto3" json:"arguments,omitempty"`
}

func (m *CustomError) Reset()         { *m = CustomError{} }
func (m *CustomError) String() string { return proto.CompactTextString(m) }
func (*CustomError) ProtoMessage()    {}
func (*CustomError) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8a57ab2f9f14837, []int{5}
}
func (m *CustomError) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CustomError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CustomError.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CustomError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomError.Merge(m, src)
}
func (m *CustomError) XXX_Size() int {
	return m.Size()
}
func (m *CustomError) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomError.DiscardUnknown(m)
}

var xxx_messageInfo_CustomError proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ChainConfig)(nil), "relayer.chains.ethereum.config.ChainConfig")
	proto.RegisterType((*AllowLCFunctionsConfig)(nil), "relayer.chains.ethereum.config.AllowLCFunctionsConfig")
	proto.RegisterType((*Fraction)(nil), "relayer.chains.ethereum.config.Fraction")
	proto.RegisterType((*DynamicTxGasConfig)(nil), "relayer.chains.ethereum.config.DynamicTxGasConfig")
	proto.RegisterType((*Argument)(nil), "relayer.chains.ethereum.config.Argument")
	proto.RegisterType((*CustomError)(nil), "relayer.chains.ethereum.config.CustomError")
}

func init() {
	proto.RegisterFile("relayer/chains/ethereum/config/config.proto", fileDescriptor_a8a57ab2f9f14837)
}

var fileDescriptor_a8a57ab2f9f14837 = []byte{
	// 923 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xcd, 0x6e, 0x1b, 0x37,
	0x10, 0xb6, 0x62, 0x55, 0x96, 0x28, 0x2b, 0x71, 0x08, 0x3b, 0x5e, 0xbb, 0x8d, 0x2a, 0xa8, 0x17,
	0x15, 0x89, 0x57, 0x80, 0x8b, 0x06, 0x45, 0x6f, 0x8a, 0x12, 0xa5, 0x29, 0xdc, 0xc2, 0xd8, 0xea,
	0xd4, 0x0b, 0xc1, 0xe5, 0x8e, 0x56, 0x84, 0x77, 0xc9, 0x05, 0x49, 0x39, 0x52, 0x9f, 0xa2, 0x0f,
	0xd0, 0x07, 0xca, 0x31, 0xc7, 0x1e, 0x5b, 0xfb, 0x0d, 0xfa, 0x04, 0x05, 0xc9, 0x5d, 0x49, 0x46,
	0x8a, 0x1a, 0x39, 0x49, 0x9c, 0xef, 0x67, 0x86, 0xe4, 0x70, 0x16, 0x3d, 0x53, 0x90, 0xd1, 0x15,
	0xa8, 0x21, 0x9b, 0x53, 0x2e, 0xf4, 0x10, 0xcc, 0x1c, 0x14, 0x2c, 0xf2, 0x21, 0x93, 0x62, 0xc6,
	0xd3, 0xf2, 0x27, 0x2c, 0x94, 0x34, 0x12, 0x77, 0x4b, 0x72, 0xe8, 0xc9, 0x61, 0x45, 0x0e, 0x3d,
	0xeb, 0xf4, 0x30, 0x95, 0xa9, 0x74, 0xd4, 0xa1, 0xfd, 0xe7, 0x55, 0xa7, 0x27, 0xa9, 0x94, 0x69,
	0x06, 0x43, 0xb7, 0x8a, 0x17, 0xb3, 0x21, 0x15, 0x2b, 0x0f, 0xf5, 0xff, 0x69, 0xa0, 0xf6, 0xd8,
	0x7a, 0x8d, 0x9d, 0x01, 0x3e, 0x41, 0x4d, 0x67, 0x4d, 0x78, 0x12, 0xd4, 0x7a, 0xb5, 0x41, 0x2b,
	0xda, 0x73, 0xeb, 0xb7, 0x09, 0xee, 0xa1, 0x7d, 0x30, 0x73, 0xb2, 0x86, 0x1f, 0xf4, 0x6a, 0x83,
	0x7a, 0x84, 0xc0, 0xcc, 0xc7, 0x25, 0xe3, 0x04, 0x35, 0x55, 0xc1, 0x08, 0x4d, 0x12, 0x15, 0xec,
	0x7a, 0xb1, 0x2a, 0xd8, 0x28, 0x49, 0x14, 0x7e, 0x8e, 0x1a, 0x9a, 0xa7, 0x02, 0x54, 0x50, 0xef,
	0xd5, 0x06, 0xed, 0xf3, 0xc3, 0xd0, 0xd7, 0x14, 0x56, 0x35, 0x85, 0x23, 0xb1, 0x8a, 0x4a, 0x0e,
	0xfe, 0x12, 0xb5, 0x79, 0xec, 0x8d, 0x40, 0xeb, 0xe0, 0x33, 0xe7, 0x85, 0x78, 0xec, 0xbc, 0x40,
	0x6b, 0xfc, 0x02, 0x1d, 0x73, 0xc1, 0x0d, 0xa7, 0x19, 0xd1, 0x20, 0x12, 0xc2, 0xe6, 0xc0, 0xae,
	0x0a, 0xc9, 0x85, 0x09, 0x1a, 0xae, 0xac, 0xa3, 0x12, 0xfe, 0x05, 0x44, 0x32, 0x5e, 0x83, 0xdb,
	0x3a, 0x05, 0xec, 0x7a, 0x5b, 0xb7, 0x77, 0x47, 0x17, 0x01, 0xbb, 0xde, 0xd2, 0x3d, 0x47, 0x18,
	0x04, 0x8d, 0x33, 0x20, 0x09, 0xc4, 0x8b, 0x94, 0x18, 0x45, 0x19, 0x04, 0xcd, 0x5e, 0x6d, 0xd0,
	0x8c, 0x0e, 0x3c, 0xf2, 0xca, 0x02, 0x53, 0x1b, 0xc7, 0xdf, 0xa2, 0x63, 0x7a, 0x0d, 0x8a, 0xa6,
	0x40, 0xe2, 0x4c, 0xb2, 0x2b, 0x62, 0x78, 0x0e, 0x24, 0xd7, 0xc0, 0x82, 0x96, 0xcb, 0x72, 0x58,
	0xc2, 0x2f, 0x2d, 0x3a, 0xe5, 0x39, 0xfc, 0xa4, 0x81, 0x59, 0x59, 0x4e, 0x97, 0x44, 0x81, 0x51,
	0x2b, 0x32, 0x93, 0x8a, 0x70, 0xc1, 0xb2, 0x85, 0xe6, 0x52, 0x04, 0xc8, 0xcb, 0x72, 0xba, 0x8c,
	0x2c, 0x3a, 0x91, 0xea, 0x6d, 0x85, 0xe1, 0x04, 0x61, 0x9a, 0x65, 0xf2, 0x1d, 0xc9, 0x18, 0x99,
	0x2d, 0x04, 0x33, 0x5c, 0x0a, 0x1d, 0xb4, 0xdd, 0x31, 0xbf, 0x08, 0xff, 0xbf, 0x61, 0xc2, 0x91,
	0x55, 0x5e, 0x8c, 0x27, 0x95, 0xce, 0xb7, 0x41, 0x74, 0xe0, 0x1c, 0x2f, 0xd8, 0x3a, 0x8e, 0xa7,
	0xe8, 0x71, 0x4a, 0x35, 0x01, 0x6d, 0x78, 0x4e, 0x0d, 0x10, 0x45, 0x0d, 0x04, 0xfb, 0x2e, 0xc9,
	0xe0, 0xbe, 0x24, 0x13, 0x45, 0x9d, 0x4b, 0xf4, 0x28, 0xa5, 0xfa, 0x75, 0xe9, 0x10, 0x51, 0x03,
	0xb8, 0x8f, 0x3a, 0x76, 0xcb, 0xd6, 0x39, 0xe3, 0x39, 0x37, 0x41, 0xc7, 0x6d, 0xb4, 0x9d, 0xd3,
	0xe5, 0x1b, 0xaa, 0x2f, 0x6c, 0x08, 0x1f, 0xa3, 0x3d, 0xb3, 0x24, 0x66, 0x55, 0x40, 0xf0, 0xd0,
	0x35, 0x42, 0xc3, 0x2c, 0xa7, 0xab, 0x02, 0x30, 0xa0, 0xa3, 0x64, 0x25, 0x68, 0xce, 0x19, 0x31,
	0xde, 0xc3, 0xe7, 0x0b, 0x1e, 0xb9, 0xb2, 0xce, 0xef, 0x2b, 0xeb, 0x95, 0x17, 0x4f, 0x6d, 0xaa,
	0x72, 0xdf, 0x38, 0xf9, 0x28, 0x86, 0x2f, 0x51, 0x87, 0x2d, 0xb4, 0x91, 0x39, 0x01, 0xa5, 0xa4,
	0xd2, 0xc1, 0x41, 0x6f, 0x77, 0xd0, 0x3e, 0x7f, 0x76, 0x9f, 0xfd, 0xd8, 0x89, 0x5e, 0x5b, 0x4d,
	0xb4, 0xcf, 0x36, 0x0b, 0xdd, 0x57, 0xe8, 0xc9, 0x7f, 0x9f, 0x3b, 0x7e, 0x8a, 0x50, 0xb6, 0xe9,
	0x7b, 0xff, 0x00, 0x5b, 0xd9, 0xba, 0xed, 0x3f, 0x47, 0x2d, 0x7f, 0xd5, 0x34, 0xcb, 0xdc, 0xfb,
	0x6b, 0x46, 0x4d, 0x17, 0x18, 0x65, 0x19, 0xfe, 0x02, 0xb5, 0x34, 0x64, 0xc0, 0x8c, 0xad, 0x71,
	0xb7, 0xb7, 0x6b, 0xa5, 0xeb, 0x40, 0xff, 0x47, 0xd4, 0xac, 0xae, 0xc1, 0x32, 0xc5, 0x22, 0x07,
	0x45, 0x8d, 0x54, 0x2e, 0x49, 0x3d, 0xda, 0x04, 0x70, 0x0f, 0xb5, 0x13, 0x10, 0x32, 0xe7, 0xc2,
	0xe1, 0xfe, 0x99, 0x6f, 0x87, 0xfa, 0x7f, 0xec, 0x22, 0xfc, 0xf1, 0xe1, 0xe1, 0xef, 0xd1, 0xa9,
	0xbb, 0x44, 0x52, 0x28, 0x2e, 0x15, 0x37, 0x2b, 0x32, 0x03, 0x20, 0x05, 0x28, 0x7b, 0x37, 0xe5,
	0x66, 0x9e, 0x38, 0xc6, 0x65, 0x49, 0x98, 0x00, 0x5c, 0x82, 0x7a, 0x43, 0x5d, 0x7b, 0xdd, 0x51,
	0xb9, 0xf6, 0x7a, 0xf0, 0xa9, 0xed, 0x55, 0x6c, 0x7c, 0x5d, 0x7b, 0x7d, 0x8d, 0x1e, 0xfb, 0x8a,
	0xb6, 0x0b, 0xf1, 0x93, 0xe9, 0xa1, 0x03, 0x36, 0x05, 0x5c, 0xa0, 0x4e, 0x4c, 0x35, 0x6c, 0x92,
	0xd7, 0x3f, 0x31, 0x79, 0xdb, 0xca, 0xab, 0xc4, 0x23, 0xf4, 0xd4, 0x1a, 0xcd, 0xb9, 0x36, 0x52,
	0xad, 0x88, 0x82, 0x77, 0x54, 0x25, 0xb6, 0x02, 0x06, 0xc2, 0xf0, 0x0c, 0xdc, 0x48, 0xeb, 0x44,
	0xa7, 0x33, 0x80, 0x1f, 0x3c, 0x27, 0x72, 0x94, 0xcb, 0x35, 0x03, 0x7f, 0x87, 0x4e, 0xee, 0x4e,
	0x83, 0x2d, 0x43, 0x37, 0xe4, 0x3a, 0xd1, 0xd1, 0xd6, 0x3c, 0x98, 0xac, 0x9d, 0xfa, 0x5d, 0xd4,
	0x1c, 0xa9, 0x74, 0x91, 0x83, 0x30, 0x18, 0xa3, 0xba, 0x7b, 0x39, 0xfe, 0xf4, 0xdd, 0xff, 0xfe,
	0x6f, 0xa8, 0xbd, 0xd5, 0x9b, 0xf8, 0x2b, 0xd4, 0xa9, 0xc6, 0x06, 0x11, 0x34, 0xaf, 0xb8, 0xfb,
	0x55, 0xf0, 0x67, 0x9a, 0x03, 0x9e, 0xa0, 0x16, 0x2d, 0x3d, 0x75, 0xf0, 0xc0, 0x3d, 0x80, 0x7b,
	0x8f, 0xa6, 0x2a, 0x22, 0xda, 0x48, 0x5f, 0xd2, 0xf7, 0x7f, 0x77, 0x77, 0xde, 0xdf, 0x74, 0x6b,
	0x1f, 0x6e, 0xba, 0xb5, 0xbf, 0x6e, 0xba, 0xb5, 0xdf, 0x6f, 0xbb, 0x3b, 0x1f, 0x6e, 0xbb, 0x3b,
	0x7f, 0xde, 0x76, 0x77, 0x7e, 0x1d, 0xa7, 0xdc, 0xcc, 0x17, 0x71, 0xc8, 0x64, 0x3e, 0x4c, 0xa8,
	0xa1, 0xce, 0x38, 0xa3, 0xf1, 0xfa, 0xa3, 0x78, 0xc6, 0x63, 0x76, 0xe6, 0xd2, 0x9e, 0x39, 0x6c,
	0x58, 0x5c, 0xa5, 0x43, 0xb7, 0x5e, 0x53, 0xe2, 0x86, 0xfb, 0xa4, 0x7c, 0xf3, 0x6f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xad, 0x75, 0x8c, 0xf8, 0x59, 0x07, 0x00, 0x00,
}

func (m *ChainConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ChainConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ChainConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CustomErrors) > 0 {
		for iNdEx := len(m.CustomErrors) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CustomErrors[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintConfig(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x82
		}
	}
	if m.DynamicTxGasConfig != nil {
		{
			size, err := m.DynamicTxGasConfig.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintConfig(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x7a
	}
	if len(m.TxType) > 0 {
		i -= len(m.TxType)
		copy(dAtA[i:], m.TxType)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.TxType)))
		i--
		dAtA[i] = 0x72
	}
	if m.MaxGasLimit != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.MaxGasLimit))
		i--
		dAtA[i] = 0x68
	}
	if m.GasEstimateRate != nil {
		{
			size, err := m.GasEstimateRate.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintConfig(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x62
	}
	if m.AllowLcFunctions != nil {
		{
			size, err := m.AllowLcFunctions.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintConfig(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x5a
	}
	if m.MaxRetryForInclusion != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.MaxRetryForInclusion))
		i--
		dAtA[i] = 0x50
	}
	if m.AverageBlockTimeMsec != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.AverageBlockTimeMsec))
		i--
		dAtA[i] = 0x48
	}
	if m.EnableDebugTrace {
		i--
		if m.EnableDebugTrace {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if m.InitialRecvCheckpoint != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.InitialRecvCheckpoint))
		i--
		dAtA[i] = 0x38
	}
	if m.InitialSendCheckpoint != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.InitialSendCheckpoint))
		i--
		dAtA[i] = 0x30
	}
	if len(m.IbcAddress) > 0 {
		i -= len(m.IbcAddress)
		copy(dAtA[i:], m.IbcAddress)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.IbcAddress)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Signer != nil {
		{
			size, err := m.Signer.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintConfig(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.RpcAddr) > 0 {
		i -= len(m.RpcAddr)
		copy(dAtA[i:], m.RpcAddr)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.RpcAddr)))
		i--
		dAtA[i] = 0x1a
	}
	if m.EthChainId != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.EthChainId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AllowLCFunctionsConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AllowLCFunctionsConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AllowLCFunctionsConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Selectors) > 0 {
		for iNdEx := len(m.Selectors) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Selectors[iNdEx])
			copy(dAtA[i:], m.Selectors[iNdEx])
			i = encodeVarintConfig(dAtA, i, uint64(len(m.Selectors[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.AllowAll {
		i--
		if m.AllowAll {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.LcAddress) > 0 {
		i -= len(m.LcAddress)
		copy(dAtA[i:], m.LcAddress)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.LcAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Fraction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Fraction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Fraction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Denominator != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.Denominator))
		i--
		dAtA[i] = 0x10
	}
	if m.Numerator != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.Numerator))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DynamicTxGasConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DynamicTxGasConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DynamicTxGasConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxRetryForFeeHistory != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.MaxRetryForFeeHistory))
		i--
		dAtA[i] = 0x30
	}
	if m.FeeHistoryRewardPercentile != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.FeeHistoryRewardPercentile))
		i--
		dAtA[i] = 0x28
	}
	if m.BaseFeeRate != nil {
		{
			size, err := m.BaseFeeRate.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintConfig(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.LimitFeePerGas) > 0 {
		i -= len(m.LimitFeePerGas)
		copy(dAtA[i:], m.LimitFeePerGas)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.LimitFeePerGas)))
		i--
		dAtA[i] = 0x1a
	}
	if m.PriorityFeeRate != nil {
		{
			size, err := m.PriorityFeeRate.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintConfig(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.LimitPriorityFeePerGas) > 0 {
		i -= len(m.LimitPriorityFeePerGas)
		copy(dAtA[i:], m.LimitPriorityFeePerGas)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.LimitPriorityFeePerGas)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Argument) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Argument) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Argument) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Type) > 0 {
		i -= len(m.Type)
		copy(dAtA[i:], m.Type)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.Type)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CustomError) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CustomError) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CustomError) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Arguments) > 0 {
		for iNdEx := len(m.Arguments) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Arguments[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintConfig(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.FunctionName) > 0 {
		i -= len(m.FunctionName)
		copy(dAtA[i:], m.FunctionName)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.FunctionName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintConfig(dAtA []byte, offset int, v uint64) int {
	offset -= sovConfig(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ChainConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	if m.EthChainId != 0 {
		n += 1 + sovConfig(uint64(m.EthChainId))
	}
	l = len(m.RpcAddr)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	if m.Signer != nil {
		l = m.Signer.Size()
		n += 1 + l + sovConfig(uint64(l))
	}
	l = len(m.IbcAddress)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	if m.InitialSendCheckpoint != 0 {
		n += 1 + sovConfig(uint64(m.InitialSendCheckpoint))
	}
	if m.InitialRecvCheckpoint != 0 {
		n += 1 + sovConfig(uint64(m.InitialRecvCheckpoint))
	}
	if m.EnableDebugTrace {
		n += 2
	}
	if m.AverageBlockTimeMsec != 0 {
		n += 1 + sovConfig(uint64(m.AverageBlockTimeMsec))
	}
	if m.MaxRetryForInclusion != 0 {
		n += 1 + sovConfig(uint64(m.MaxRetryForInclusion))
	}
	if m.AllowLcFunctions != nil {
		l = m.AllowLcFunctions.Size()
		n += 1 + l + sovConfig(uint64(l))
	}
	if m.GasEstimateRate != nil {
		l = m.GasEstimateRate.Size()
		n += 1 + l + sovConfig(uint64(l))
	}
	if m.MaxGasLimit != 0 {
		n += 1 + sovConfig(uint64(m.MaxGasLimit))
	}
	l = len(m.TxType)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	if m.DynamicTxGasConfig != nil {
		l = m.DynamicTxGasConfig.Size()
		n += 1 + l + sovConfig(uint64(l))
	}
	if len(m.CustomErrors) > 0 {
		for _, e := range m.CustomErrors {
			l = e.Size()
			n += 2 + l + sovConfig(uint64(l))
		}
	}
	return n
}

func (m *AllowLCFunctionsConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.LcAddress)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	if m.AllowAll {
		n += 2
	}
	if len(m.Selectors) > 0 {
		for _, s := range m.Selectors {
			l = len(s)
			n += 1 + l + sovConfig(uint64(l))
		}
	}
	return n
}

func (m *Fraction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Numerator != 0 {
		n += 1 + sovConfig(uint64(m.Numerator))
	}
	if m.Denominator != 0 {
		n += 1 + sovConfig(uint64(m.Denominator))
	}
	return n
}

func (m *DynamicTxGasConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.LimitPriorityFeePerGas)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	if m.PriorityFeeRate != nil {
		l = m.PriorityFeeRate.Size()
		n += 1 + l + sovConfig(uint64(l))
	}
	l = len(m.LimitFeePerGas)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	if m.BaseFeeRate != nil {
		l = m.BaseFeeRate.Size()
		n += 1 + l + sovConfig(uint64(l))
	}
	if m.FeeHistoryRewardPercentile != 0 {
		n += 1 + sovConfig(uint64(m.FeeHistoryRewardPercentile))
	}
	if m.MaxRetryForFeeHistory != 0 {
		n += 1 + sovConfig(uint64(m.MaxRetryForFeeHistory))
	}
	return n
}

func (m *Argument) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Type)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	return n
}

func (m *CustomError) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FunctionName)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	if len(m.Arguments) > 0 {
		for _, e := range m.Arguments {
			l = e.Size()
			n += 1 + l + sovConfig(uint64(l))
		}
	}
	return n
}

func sovConfig(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozConfig(x uint64) (n int) {
	return sovConfig(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ChainConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ChainConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ChainConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EthChainId", wireType)
			}
			m.EthChainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EthChainId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RpcAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RpcAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Signer == nil {
				m.Signer = &types.Any{}
			}
			if err := m.Signer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IbcAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IbcAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialSendCheckpoint", wireType)
			}
			m.InitialSendCheckpoint = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InitialSendCheckpoint |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialRecvCheckpoint", wireType)
			}
			m.InitialRecvCheckpoint = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InitialRecvCheckpoint |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnableDebugTrace", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.EnableDebugTrace = bool(v != 0)
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AverageBlockTimeMsec", wireType)
			}
			m.AverageBlockTimeMsec = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AverageBlockTimeMsec |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxRetryForInclusion", wireType)
			}
			m.MaxRetryForInclusion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxRetryForInclusion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowLcFunctions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AllowLcFunctions == nil {
				m.AllowLcFunctions = &AllowLCFunctionsConfig{}
			}
			if err := m.AllowLcFunctions.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasEstimateRate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.GasEstimateRate == nil {
				m.GasEstimateRate = &Fraction{}
			}
			if err := m.GasEstimateRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxGasLimit", wireType)
			}
			m.MaxGasLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxGasLimit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DynamicTxGasConfig", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DynamicTxGasConfig == nil {
				m.DynamicTxGasConfig = &DynamicTxGasConfig{}
			}
			if err := m.DynamicTxGasConfig.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CustomErrors", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CustomErrors = append(m.CustomErrors, &CustomError{})
			if err := m.CustomErrors[len(m.CustomErrors)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AllowLCFunctionsConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AllowLCFunctionsConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AllowLCFunctionsConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LcAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LcAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowAll", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AllowAll = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Selectors", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Selectors = append(m.Selectors, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Fraction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Fraction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Fraction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Numerator", wireType)
			}
			m.Numerator = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Numerator |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denominator", wireType)
			}
			m.Denominator = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Denominator |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DynamicTxGasConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DynamicTxGasConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DynamicTxGasConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LimitPriorityFeePerGas", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LimitPriorityFeePerGas = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PriorityFeeRate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PriorityFeeRate == nil {
				m.PriorityFeeRate = &Fraction{}
			}
			if err := m.PriorityFeeRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LimitFeePerGas", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LimitFeePerGas = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseFeeRate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BaseFeeRate == nil {
				m.BaseFeeRate = &Fraction{}
			}
			if err := m.BaseFeeRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeHistoryRewardPercentile", wireType)
			}
			m.FeeHistoryRewardPercentile = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FeeHistoryRewardPercentile |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxRetryForFeeHistory", wireType)
			}
			m.MaxRetryForFeeHistory = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxRetryForFeeHistory |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Argument) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Argument: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Argument: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CustomError) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CustomError: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CustomError: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FunctionName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FunctionName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Arguments", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Arguments = append(m.Arguments, &Argument{})
			if err := m.Arguments[len(m.Arguments)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipConfig(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthConfig
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupConfig
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthConfig
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthConfig        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowConfig          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupConfig = fmt.Errorf("proto: unexpected end of group")
)
