// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: relayer/chains/ethereum/signers/hd/config.proto

package hd

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SignerConfig struct {
	Mnemonic string `protobuf:"bytes,1,opt,name=mnemonic,proto3" json:"mnemonic,omitempty"`
	Path     string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (m *SignerConfig) Reset()         { *m = SignerConfig{} }
func (m *SignerConfig) String() string { return proto.CompactTextString(m) }
func (*SignerConfig) ProtoMessage()    {}
func (*SignerConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_a221898db767a8da, []int{0}
}
func (m *SignerConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SignerConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SignerConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SignerConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignerConfig.Merge(m, src)
}
func (m *SignerConfig) XXX_Size() int {
	return m.Size()
}
func (m *SignerConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_SignerConfig.DiscardUnknown(m)
}

var xxx_messageInfo_SignerConfig proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SignerConfig)(nil), "relayer.chains.ethereum.signers.hd.SignerConfig")
}

func init() {
	proto.RegisterFile("relayer/chains/ethereum/signers/hd/config.proto", fileDescriptor_a221898db767a8da)
}

var fileDescriptor_a221898db767a8da = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0x21, 0x4f, 0x04, 0x31,
	0x10, 0x85, 0x5b, 0x42, 0x08, 0x34, 0xa8, 0x06, 0x71, 0x39, 0xd1, 0x90, 0x53, 0x98, 0xed, 0x08,
	0x3c, 0x02, 0x3c, 0x02, 0x1c, 0xae, 0xed, 0x96, 0xb6, 0x61, 0xdb, 0x6e, 0xba, 0x3d, 0xc1, 0xbf,
	0xe0, 0x67, 0x9d, 0x3c, 0x89, 0x84, 0xdd, 0x3f, 0x42, 0x98, 0x5d, 0x56, 0xe1, 0xde, 0xcc, 0xbc,
	0x6f, 0xf2, 0x1e, 0x83, 0x62, 0x3b, 0xf5, 0x6e, 0x0b, 0x18, 0xaf, 0x42, 0x1a, 0xc0, 0x56, 0x6f,
	0x8b, 0xdd, 0x47, 0x18, 0x82, 0x4b, 0xb6, 0x0c, 0xe0, 0x5b, 0x30, 0x39, 0xbd, 0x06, 0x27, 0xfb,
	0x92, 0x6b, 0xe6, 0xbb, 0x05, 0x90, 0x33, 0x20, 0xff, 0x00, 0xb9, 0x00, 0xd2, 0xb7, 0xdb, 0x2b,
	0x97, 0x5d, 0x46, 0x3b, 0xfc, 0xaa, 0x99, 0xdc, 0xdd, 0xb1, 0xcb, 0x67, 0xf4, 0x3c, 0xe0, 0x3f,
	0xbe, 0x65, 0xe7, 0x31, 0xd9, 0x98, 0x53, 0x30, 0x1b, 0x7a, 0x4d, 0x6f, 0x2e, 0x9e, 0xd6, 0x99,
	0x73, 0x76, 0xda, 0xab, 0xea, 0x37, 0x27, 0xb8, 0x47, 0x7d, 0xdf, 0x1d, 0xbe, 0x05, 0x39, 0x8c,
	0x82, 0x1e, 0x47, 0x41, 0xbf, 0x46, 0x41, 0x3f, 0x26, 0x41, 0x8e, 0x93, 0x20, 0x9f, 0x93, 0x20,
	0x2f, 0x8f, 0x2e, 0x54, 0xbf, 0xd7, 0xd2, 0xe4, 0x08, 0xad, 0xaa, 0x0a, 0xe3, 0x75, 0x4a, 0xaf,
	0x8d, 0x9a, 0xa0, 0x4d, 0x83, 0xe1, 0x1b, 0xbc, 0x41, 0xff, 0xe6, 0xe6, 0xf6, 0xff, 0x95, 0xd6,
	0x67, 0x18, 0xfa, 0xf6, 0x27, 0x00, 0x00, 0xff, 0xff, 0x78, 0xa9, 0x5c, 0xa2, 0x21, 0x01, 0x00,
	0x00,
}

func (m *SignerConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SignerConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SignerConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Path) > 0 {
		i -= len(m.Path)
		copy(dAtA[i:], m.Path)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.Path)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Mnemonic) > 0 {
		i -= len(m.Mnemonic)
		copy(dAtA[i:], m.Mnemonic)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.Mnemonic)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintConfig(dAtA []byte, offset int, v uint64) int {
	offset -= sovConfig(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SignerConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Mnemonic)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	l = len(m.Path)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	return n
}

func sovConfig(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozConfig(x uint64) (n int) {
	return sovConfig(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SignerConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SignerConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SignerConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mnemonic", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mnemonic = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Path", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Path = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipConfig(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthConfig
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupConfig
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthConfig
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthConfig        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowConfig          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupConfig = fmt.Errorf("proto: unexpected end of group")
)
